# Generated by Django 5.0 on 2024-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.IntegerField(blank=True, null=True)),
                ('cat_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('template_type', models.IntegerField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('preview_image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_paid', models.IntegerField(blank=True, null=True)),
                ('is_favorite', models.IntegerField(blank=True, null=True)),
                ('visit_count', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_new', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
