# Generated by Django 5.0 on 2024-04-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_template_poster_id_template_preview_image_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='preview_image_url',
            new_name='preview_image',
        ),
    ]
