# Generated by Django 5.0 on 2024-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_preview_image_url_template_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='preview_image_file',
            field=models.FileField(blank=True, null=True, upload_to='preview_image_file/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_file/'),
        ),
    ]
